:PROPERTIES:
:ID:       0CBCCEE0-6392-4EC6-BC6A-AB837306B7EB
:ROAM_ALIASES: ox-html-markdown-style-footnotes
:END:
#+title: Export Org documents with Markdown-style footnotes
#+author: Jeff Kreeftmeijer
#+date: 2023-03-26

#+headers: :eval no
#+begin_src org :tangle test/fixtures/footnote.org
  Hello, world![fn:1]

  [fn:1] A footnote.
#+end_src

The Org document above produces the following footnotes when exported to HTML:

#+headers: :cache yes
#+headers: :exports results
#+headers: :results scalar
#+headers: :wrap src html
#+begin_src shell
  emacs /tmp/footnote.org --batch \
        --eval '(setq org-html-doctype "html5")' \
        --eval '(setq org-html-head-include-default-style nil)' \
        --eval '(setq org-html-preamble nil)' \
        --eval '(setq org-html-postamble nil)' \
        --funcall org-html-export-to-html
  cat /tmp/footnote.html | tail -n9 | head -n3
#+end_src

#+RESULTS[fb44facc58c83460d313d31b252a26c77765811e]:
#+begin_src html
<div class="footdef"><sup><a id="fn.1" class="footnum" href="#fnr.1" role="doc-backlink">1</a></sup> <div class="footpara" role="doc-footnote"><p class="footpara">
A footnote.
</p></div></div>
#+end_src

Footnotes consist of a link back to the place the footnote was referenced in the document and a =<div>= with the footnote's contents.
The contents div, being a block element, is printed on a seperate line unless the default styling is loaded.
The styling makes the footnotes appear inline, which places them behind the footnote link, but also inlines each paragraph for multi-paragraph footnotes.

Some flavors of Markdown use [[https://www.markdownguide.org/extended-syntax/#footnotes][ordered lists for footnotes]].
These don't rely on styling, and they don't inline paragraphs in the footnotes.

To use Markdown-style footnotes in Org, advise the =org-html-footnote-section= function.
This new function keeps most of the output the same, but uses an ordered list instead of nested =<div>= elements.
It also uses a backlink with an arrow, which resembles the Markdown tradition:

#+headers: :exports none
#+headers: :tangle ox-html-markdown-style-footnotes.el
#+begin_src emacs-lisp
  ;;; ox-html-markdown-style-footnotes.el --- Markdown-style footnotes for ox-html.el

  ;;; Commentary:

  ;; ox-html-markdown-style-footnotes replaces the ox-html's default
  ;; footnotes with an HTML ordered list, inspired by footnotes sections
  ;; of some Markdown implementations.

  ;;; Code:
#+end_src

#+headers: :tangle ox-html-markdown-style-footnotes.el
#+begin_src emacs-lisp
  (require 'ox-html)

  (defun org-html-markdown-style-footnotes--section (orig-fun &rest args)
    "Replace ORIG-FUN with a Markdown-style footnotes section.
          ARGS contains the info plist, which is used as a communication channel."
    (let ((info (car args)))
      (pcase (org-export-collect-footnote-definitions info)
        (`nil nil)
        (definitions
         (format "<hr>\n<ol>\n%s</ol>\n"
                 (mapconcat
                  (lambda (definition)
                    (pcase definition
                      (`(,n ,_ ,def)
                       (format
                        "<li class=\"footdef\" id=\"fn.%d\">%s%s</li>\n"
                        n
                        (format "<div class=\"footpara\" role=\"doc-footnote\">%s</div>" (org-trim (org-export-data def info)))
                        (format "<a href=\"#fnr.%d\" role=\"doc-backlink\">↩&#65038;</a>" n)))))
                  definitions
                  "\n"))))))

  ;;;###autoload
  (defun org-html-markdown-style-footnotes-add ()
    (interactive)
    (advice-add 'org-html-footnote-section
                :around #'org-html-markdown-style-footnotes--section))

  (defun org-html-markdown-style-footnotes-remove ()
    (interactive)
    (advice-remove 'org-html-footnote-section
                   #'org-html-markdown-style-footnotes--section))

  (provide 'ox-html-markdown-style-footnotes)
#+end_src

#+headers: :exports none
#+headers: :tangle org-html-markdown-style-footnotes.el
#+begin_src emacs-lisp
;;; ox-html-markdown-style-footnotes.el ends here
#+end_src

After adding the advise with =org-html-markdown-style-footnotes-add=, the exported footnotes are Markdown-style unordered lists:

#+headers: :cache yes
#+headers: :exports results
#+headers: :results scalar
#+headers: :wrap src html
#+begin_src shell
  emacs --batch \
        --load=ox-html-markdown-style-footnotes.el \
        --file=/tmp/footnote-2.org \
        --eval '(setq org-html-doctype "html5")' \
        --eval '(setq org-html-head-include-default-style nil)' \
        --eval '(setq org-html-preamble nil)' \
        --eval '(setq org-html-postamble nil)' \
        --eval '(org-html-markdown-style-footnotes-add)' \
        --funcall org-html-export-to-html
  cat /tmp/footnote-2.html | tail -n13 | head -n10
#+end_src

#+RESULTS[e4aeb3dc67f0eb11396d406b613758c0632af791]:
#+begin_src html
<hr>
<ol>
<li class="footdef" id="fn.1"><div class="footpara" role="doc-footnote"><p class="footpara">
A footnote.
</p>

<p class="footpara">
With a second paragraph.
</p></div><a href="#fnr.1" role="doc-backlink">↩&#65038;</a></li>
</ol>
#+end_src
